name: Example workflow using Snyk
on: workflow_dispatch:
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          name: "Snyk Code Test"
  Pipeline-Job:
    # Configure Environment
    name: 'Snyk Test'
    runs-on: ubuntu-latest
    env: 
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
       
    steps:
    # Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v1

    # Install and Authenticate to Snyk
    - name: Install Snyk & Authenticate
      run: |
         sudo npm install -g snyk
         wget https://raw.githubusercontent.com/metalstormbass/snyk-code-helper/main/snyk-code-helper-nc.sh
         chmod +x ./snyk-code-helper-nc.sh
         snyk auth ${SNYK_TOKEN}
    # Run Snyk Code
    - name: Run Snyk Code
      run: |
         snyk code test --json | ./snyk-code-helper-nc.sh
         snyk code test --sarif  > results.sarif 
         
      continue-on-error: true
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        # Path to SARIF file relative to the root of the repository
        sarif_file: results.sarif
