name: Example workflow using Snyk

on: 
  workflow_dispatch: {}

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Snyk Code Test"
        uses: snyk/actions/node@master
        with:
          command: monitor
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  Pipeline-Job:
    name: 'Snyk Test'
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Snyk & Authenticate
        run: |
          sudo npm install -g snyk
          snyk auth ${SNYK_TOKEN}

      - name: Run Snyk Code
        run: |
          snyk code test --json | ./snyk-code-helper-nc.sh
          snyk code test --sarif > results.sarif
        continue-on-error: true

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
